## TOML version catalog for the BasicGame-on-Gradle project

[versions]
## select one version of JMonkeyEngine:
#jme = "3.1.0-stable"
#jme = "3.2.4-stable"
#jme = "3.3.2-stable"
#jme = "3.4.1-stable"
#jme = "3.5.2-stable"
jme = "3.6.1-stable"
#jme = "3.7.0-beta1"
#jme = "3.8.0-SNAPSHOT"

[libraries]
blocks = { module = "com.github.rvandoosselaer:Blocks", version = "1.7.1" }
groovy-jsr223 = { module = "org.codehaus.groovy:groovy-jsr223", version = "3.0.21" }
heart = { module = "com.github.stephengold:Heart", version = "9.0.0" }
jme3-awt-dialogs = { module = "org.jmonkeyengine:jme3-awt-dialogs", version.ref = "jme" }
jme3-core = { module = "org.jmonkeyengine:jme3-core", version.ref = "jme" }
jme3-desktop = { module = "org.jmonkeyengine:jme3-desktop", version.ref = "jme" }
jme3-effects = { module = "org.jmonkeyengine:jme3-effects", version.ref = "jme" }
jme3-jbullet = { module = "org.jmonkeyengine:jme3-jbullet", version.ref = "jme" }
jme3-jogg = { module = "org.jmonkeyengine:jme3-jogg", version.ref = "jme" }
jme3-lwjgl = { module = "org.jmonkeyengine:jme3-lwjgl", version.ref = "jme" }
jme3-lwjgl3 = { module = "org.jmonkeyengine:jme3-lwjgl3", version.ref = "jme" }
jme3-networking = { module = "org.jmonkeyengine:jme3-networking", version.ref = "jme" }
jme3-niftygui = { module = "org.jmonkeyengine:jme3-niftygui", version.ref = "jme" }
jme3-plugins = { module = "org.jmonkeyengine:jme3-plugins", version.ref = "jme" }
jme3-terrain = { module = "org.jmonkeyengine:jme3-terrain", version.ref = "jme" }
jme3-testdata = { module = "org.jmonkeyengine:jme3-testdata", version.ref = "jme" }
jmePower = { module = "com.github.stephengold:JmePower", version = "1.1.1" }
lemur = { module = "com.simsilica:lemur", version = "1.16.0" }
lemur-props = { module = "com.simsilica:lemur-props", version = "1.2.0" }
lemur-proto = { module = "com.simsilica:lemur-proto", version = "1.13.0" }
minie = { module = "com.github.stephengold:Minie", version = "8.1.0" }
sim-math = { module = "com.simsilica:sim-math", version = "1.6.0" }
skyControl = { module = "com.github.stephengold:SkyControl", version = "1.0.5" }

[plugins]
