## catalog of libraries and plugins used to build the BasicGame-on-Gradle project

## You can read more about catalogs here:
## https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]

## select one version of JMonkeyEngine:
#jme = "3.1.0-stable"
#jme = "3.2.4-stable"
#jme = "3.3.2-stable"
#jme = "3.4.1-stable"
#jme = "3.5.2-stable"
jme = "3.6.1-stable"
#jme = "3.7.0-beta1.2.2"
#jme = "3.8.0-SNAPSHOT"

jolt-jni = "0.5.0"

[libraries]

blocks = "com.github.rvandoosselaer:Blocks:1.7.1"
groovy-jsr223 = "org.codehaus.groovy:groovy-jsr223:3.0.22"
heart = "com.github.stephengold:Heart:9.1.0"

## jme3-awt-dialogs is available only for JMonkeyEngine 3.6.0 and later:
jme3-awt-dialogs = { module = "org.jmonkeyengine:jme3-awt-dialogs", version.ref = "jme" }

jme3-core = { module = "org.jmonkeyengine:jme3-core", version.ref = "jme" }
jme3-desktop = { module = "org.jmonkeyengine:jme3-desktop", version.ref = "jme" }
jme3-effects = { module = "org.jmonkeyengine:jme3-effects", version.ref = "jme" }
jme3-jbullet = { module = "org.jmonkeyengine:jme3-jbullet", version.ref = "jme" }
jme3-jogg = { module = "org.jmonkeyengine:jme3-jogg", version.ref = "jme" }
jme3-lwjgl = { module = "org.jmonkeyengine:jme3-lwjgl", version.ref = "jme" }
jme3-lwjgl3 = { module = "org.jmonkeyengine:jme3-lwjgl3", version.ref = "jme" }
jme3-networking = { module = "org.jmonkeyengine:jme3-networking", version.ref = "jme" }
jme3-niftygui = { module = "org.jmonkeyengine:jme3-niftygui", version.ref = "jme" }
jme3-plugins = { module = "org.jmonkeyengine:jme3-plugins", version.ref = "jme" }
jme3-terrain = { module = "org.jmonkeyengine:jme3-terrain", version.ref = "jme" }
jme3-testdata = { module = "org.jmonkeyengine:jme3-testdata", version.ref = "jme" }
jmePower = "com.github.stephengold:JmePower:1.1.1"
jolt-jni-linux64 = { module = "com.github.stephengold:jolt-jni-Linux64", version.ref = "jolt-jni" }
jolt-jni-linuxarm32hf = { module = "com.github.stephengold:jolt-jni-Linux_ARM32hf", version.ref = "jolt-jni" }
jolt-jni-linuxarm64 = { module = "com.github.stephengold:jolt-jni-Linux_ARM64", version.ref = "jolt-jni" }
jolt-jni-macosx64 = { module = "com.github.stephengold:jolt-jni-MacOSX64", version.ref = "jolt-jni" }
jolt-jni-macosxarm64 = { module = "com.github.stephengold:jolt-jni-MacOSX_ARM64", version.ref = "jolt-jni" }
jolt-jni-windows64 = { module = "com.github.stephengold:jolt-jni-Windows64", version.ref = "jolt-jni" }
kk-physics = "com.github.stephengold:kk-physics:0.3.0"
lemur = "com.simsilica:lemur:1.16.0"
lemur-props = "com.simsilica:lemur-props:1.2.0"
lemur-proto = "com.simsilica:lemur-proto:1.13.0"
minie = "com.github.stephengold:Minie:8.2.0"
sim-math = "com.simsilica:sim-math:1.6.0"
skyControl = "com.github.stephengold:SkyControl:1.1.0"

[bundles]

[plugins]
